name: network
description: A new Flutter package project.
version: 0.0.1
homepage:

publish_to: none

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  shared_dependency:
    path: ../shared_dependency
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.1
  freezed: ^2.3.5
  json_serializable: ^6.7.0

flutter:
